// <auto-generated />
namespace CadastroNews.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class BDInicial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206080105131_BDInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEANVZy27jNhTdF+g/CFq1BcZyUnQwE9gzSJ24MNo4QZTONqCla4coRaoi5cbf1kU/qb/QSz1oiXpYdpppZ2dR930P70P++8+/Jh+fI+ZsIZFU8Kl7Nhq7DvBAhJRvpm6q1m/euR8/fP3V5DqMnp1PJd25pkNOLqfuk1LxhefJ4AkiIkcRDRIhxVqNAhF5JBTe+Xj8zjsbe4AiXJTlOJP7lCsaQfaAjzPBA4hVStiNCIHJ4hzf+JlUZ0kikDEJYOrOSEikSsQS/pCjBV8nxHUuGSVoiQ9sfaRZ4/faLNcoRJXXaJraPexiyNRO3bngCqokSPQz7GoHeHSXiBgStbuHdZVxEbqOV2f2bG7DazNqK6bugqvvz11nmTJGVgwP1oRJcJ347YWvRAI/AYeEKAjviFKQYH4WIWReFNG4iN8OC8h7b3yuA+IRzoUiCpPdsN6ydSkiKA31VYK4cZ05fYbwF+Ab9WSMvSHP5ckPCJ5fOUWUIY9KUmjxrV8pAgatE0fqxZ89ivNnS++SbOkmi0PDbUUDRJ3r3APLCOQTjXMMjoqXjzlynHkionvB9lz5i8cHkmxAoROi7a0v0iSwLJp4e3T2YrYQdQpqC9ZTcFth/QKQ+0BVyj4DhlqwC2n4X4K3wOXpyC2x2Y7cEtdDkHsppUBObUYdRI9tZfeah06vPXlEK55gDFOmaMzwQe2m7neNKHXJNLdzL7OISl3ieDQ6s32teNW8plnxogj8wuGr1UxEadRwVdP6oKo5w3KzD2PdqIZXdfZ9vWoIMJGyRFScaMgpAVKhaUWQXW4OJdCYXbXYGyqlTFlFShk2u5TVnWsBqsnSfhjx8mmknFq8jrFlckPiGK90ZYwpThy/mGHe+MfPKVEuwwtky7hirDWasLySDVhvdfUJYU4Tqa6IIiuii8wsjBpkBzBZaqlBs5mlEmgluf5dFMHGFDdqBcw+dnN0J8LekHkGdoabfNnwSBhJumarmWBpxHsntT45+dxTFZKfDJdghpiqEHPYlDPxrFDYAfcaEbdAb+dvUHbNPXxhfltHkkEZ7uTszo2ZQ+oJ6phs+mSVU0JVUHl2XK7zpm8nOz/9/NmuF8DWlJdFfkhaS9qBudMlvD1p9VLeDMuRl/qx82rrABkbjjWv6FcDzTsej73GIWxCmk1MC6lHQDMuDvbe7n9NhDTaoE1i8GnaodX2JkULGrDS2z0pJ3EdDMCWhrof+TupIBppgpH/O5sxijdiT3BDOF2DVA/iN9CfJ7Blnv5VwKwSUobsf/5pgOooHFyljtyuqys935IkeCJJY4F/2cZeiv0mIs/f9i8yX9rO+yopqe+qR0Tv8P75ImFWlalE4JSUnroMVvrUcZta2y5x2haJWIJEJ5cwDDD2SCyajZZ9h5t+QGPCanY3m8jgeqFDaYTab64gBq4BZ/k3WF9f7zTCretyKA5H7sbNdWXAlty9JOeNZeqGKw3/HJ4dG2LHAt23P7dJ79piX3m7rsWhsiYN2KXblvDX2Z+bAwLip/LPACJY0s1ehB58OAQ15BganEZFiWPLopLEql03oHCcVeQyUXRNAoWvA5Ay+xj3ibAUSa6jFYQLfpuqOFXoMkQrtqsGQ1+EPv3ZR4K6zZPbOPvo9m+4gGZSdAFu+Y8pZaGxe97sKV0i9A0rGpXOpdINa7MzkpaCDxRUhM8UhgeIYobC5C33yRa6bTscw3rEJleUbBISVSOYnxSW+AQ1V1SggirHXp/+Y8vT/2x9+Ae721UfCxsAAA=="; }
        }
    }
}
